### PR TITLE
Message if there are errors getting steam data

### PR DESCRIPTION
**Pull request by LaurenceWarne**
Hi! <code>steam-get-xml</code> now tells the user if there was some problem receiving the xml (e.g. profile not public), or otherwise tells the user there was no problem with the xml.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! Thank you for this, I'll review later this week. Does `steam.el` work for you (like `M-x steam-insert-org-text`)? Last time I tried I couldn't import any games, so I figured the API had changed somehow. Maybe my profile isn't public though.

**Comment by LaurenceWarne** [comment]
No problem, yep works fine, though as you say I had to set my profile to public. 

What could also be the problem is that you haven't set the "custom url" in your steam profile to match your username, so maybe <code>steam-username</code> is not the best name for that variable (I currently have set to a long number which = my steam custom url). 

You can test it by checking if https://steamcommunity.com/id/<username> goes to your profile or just check on your steam profile settings (:

**Comment by Kungsgeten** [comment]
Sorry for taking so long, but now it is merged. Thank you! I've also added information about the profile settings to the README. Actually I thought the package was broken, so I'm glad that it still works :D

**Comment by LaurenceWarne** [comment]
Nw (:

**Pull request merged**
